### PR TITLE
🐛 Check if the token has expired (#116)

### PR DESCRIPTION
**Pull request by zhujian7**
* Check if the token has expired periodically

* Requeue before the token is about to expire

* Add unit tests

---------

## Related issue(s)

Fixes #https://issues.redhat.com/browse/ACM-14261

Related PR: https://github.com/open-cluster-management-io/managed-serviceaccount/pull/116

### CODE REVIEW

**Comment by zhujian7** [comment]
Some less important code is not covered:
```
Uncovered code
New code
	return reconcile.Result{
		// Requeue even if the token is not refreshed, otherwise if the agent restarts
		// at the time that the token is not expried, no chance to trigger the expiration
		// check again
		RequeueAfter: checkTokenRefreshAfter(now, expiring, msa.Spec.Rotation.Validity.Duration),
	}, nil
```
/override "SonarCloud Code Analysis"

**Comment by xuezhaojun** [comment]
No diff with original PR, so
/lgtm

**Pull request merged**
